export const data = [
  {
    id: "10",
    img: "/hip.jpg",
    title: "Hip",
    name: "hip",
    category: "women",
  },
  {
    id: "11",
    img: "/arm.jpg",
    title: "Arm",
    name: "arm",
    category: "women",
  },
  {
    id: "12",
    img: "/breast.jpg",
    title: "Breast",
    name: "breast",
    category: "women",
  },
  {
    id: "13",
    img: "/abovebreast.jpg",
    title: " Above Breast",
    name: "aboveBreast",
    category: "women",
  },
  {
    id: "1",
    img: "/shoulders.jpg",
    title: "Shoulder",
    name: "shoulder",
    category: "women",
  },
  {
    id: "2",
    img: "/shouldertoboob.jpg",
    title: "Shoulder to Bust",
    name: "shoulderToBust",
    category: "women",
  },
  {
    id: "3",
    img: "/shouldertoneck.jpg",
    title: "Shoulder to Chest above Bust",
    name: "shoulderToChestaboveBust",
    category: "women",
  },
  {
    id: "4",
    img: "/underbreast.jpg",
    title: "Under  Breast",
    name: "underBreast",
    category: "women",
  },
  {
    id: "5",
    img: "/Untitled-1.jpg",
    title: "Shoulder to waist",
    name: "shoulderToWaist",
    category: "women",
  },
  {
    id: "6",
    img: "/waist.jpg",
    name: "waist",
    title: "Waist",
    category: "women",
  },
  {
    id: "7",
    img: "/waisttoleg.jpg",
    title: "Waist to  Leg",
    name: "waistToLeg",
    category: "women",
  },
  {
    id: "8",
    img: "/shouldertolowerboob.jpg",
    name: "shoulderToBreast",
    title: "Shoulder to Breast",
    category: "women",
  },
  {
    id: "9",
    img: "/shoulder.jpg",
    name: "armLength",
    title: "Arm length",
    category: "women",
  },
];
