const category = [
  {
    id: "1",
    title: "Women Scarf",
    description: "This is a women scarf.",
    img: "../scarf.jpg",
    price: "$25.87",
    rating: "3",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "women",
  },
  {
    id: "2",
    title: "Kids Clothes",
    img: "../kid-cloth.jpg",
    price: "$25.43",
    rating: "5",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "kids",
  },
  {
    id: "3",
    title: "Men Clothes",
    img: "../men-scarf.jpg",
    price: "$25.98",
    rating: "4",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "4",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../men-clothes.jpg",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
];
export default category;
