const category: any = [
  {
    id: "1",
    title: "Women Scarf",
    description: "This is a women scarf.",
    img: "../hab1.png",
    price: "$25.87",
    rating: "3",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "women",
  },
  {
    id: "2",
    title: "Kids Clothes",
    img: "../hab2.png",
    price: "$25.43",
    rating: "5",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "kids",
  },
  {
    id: "3",
    title: "Men Clothes",
    img: "../hab3.png",
    price: "$25.98",
    rating: "4",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "4",
    title: "Men Shirts",
    img: "../hab4.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "9",
    title: "Men Shirts",
    img: "../hab5.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "5",
    title: "Men Shirts",
    img: "../hab6.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "6",
    title: "Men Shirts",
    img: "../hab7.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "7",
    title: "Men Shirts",
    img: "../hab1.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
  {
    id: "8",
    title: "Men Shirts",
    img: "../hab3.png",
    price: "$25.56",
    rating: "2",
    available_sizes: ["S", "M", "L"],
    available_colors: ["Red"],
    purchasedNo: 2,
    type: "clothes",
    typeOfClothes: "men",
  },
];
export default category;
